### ISSUE TITLE
Add fracker deployment as a UPV

### ISSUE THREAD

**Issue by ytyukhnin** [nimbusparis/IngressRGPD#4]

**Comment by Jormund** [comment]
Do frackers really count as upv ?

**Comment by Jormund** [comment]
Tested: Using a fracker doesn't count as UPV.
Tested also using Jarvis or ADA, recharging, deploying a mod, doesn't count.
The 5 known actions that count as visits:
https://github.com/iitc-project/ingress-intel-total-conversion/issues/1083

* hacking the portal,
* deploying a resonator,
* upgrading a resonator,
* linking from the portal,
* capturing the portal.﻿
